import { prisma } from "@farm-lease/db";
import { AgreementStatus, Prisma, type Proposal } from "@prisma/client";
import { logAudit } from "../../lib/audit";
import { agreementCreatedEvent } from "../notifications/service";
import { realtime } from "../../realtime/io";

const DEFAULT_CLAUSES = [
  {
    title: "1. Parties",
    body:
      "This Lease Agreement is entered into between the Investor and the Farmer Cluster (acting through its elected Representative) for the purposes described herein.",
  },
  {
    title: "2. Term",
    body:
      "The agreement commences on the Start Date and remains in effect until the End Date, unless terminated earlier in accordance with the termination clauses below.",
  },
  {
    title: "3. Lease Payment",
    body:
      "The Investor shall pay the total amount specified in the Financial Terms via the agreed method. Payment is confirmed only after verification of the receipt by the Representative.",
  },
  {
    title: "4. Use of Land",
    body:
      "The Investor may only use the leased land for the cropping activity set out in the Financial Terms. Deviations require written consent from the Representative.",
  },
  {
    title: "5. Farmer Obligations",
    body:
      "The farmers whose land forms the cluster shall cooperate with the Investor's lawful use of the land and shall not encumber the land during the term.",
  },
  {
    title: "6. Termination",
    body:
      "Either party may terminate for material breach with 30 days written notice. Termination must be recorded via the platform for audit.",
  },
  {
    title: "7. Dispute Resolution",
    body:
      "Any dispute shall first be addressed through mediation by the Representative. Unresolved disputes will be referred to competent courts in Ethiopia.",
  },
  {
    title: "8. Digital Signatures",
    body:
      "Both parties acknowledge that electronic signatures captured through the FarmLease platform constitute valid and binding execution of this agreement.",
  },
];

/**
 * Compose an agreement draft directly from an accepted proposal.
 * Called automatically when a proposal transitions to ACCEPTED.
 * Idempotent: returns existing agreement if one already exists.
 */
export async function generateAgreementFromProposal(proposalId: string, actorId: string) {
  const existing = await prisma.agreement.findUnique({ where: { proposalId } });
  if (existing) return existing;

  const proposal = await prisma.proposal.findUnique({
    where: { id: proposalId },
    include: {
      cluster: {
        select: {
          id: true,
          name: true,
          location: true,
          region: true,
          totalArea: true,
          cropTypes: true,
          coordinates: true,
          representatives: { select: { userId: true, isPrimary: true } },
        },
      },
      investor: { select: { id: true, name: true, email: true } },
    },
  });

  if (!proposal) throw new Error("Proposal not found");

  const startDate = proposal.startDate ?? new Date();
  const endDate = addMonths(startDate, proposal.durationMonths);

  const terms = buildAgreementTerms(proposal, { startDate, endDate });

  const agreement = await prisma.agreement.create({
    data: {
      proposalId: proposal.id,
      startDate,
      endDate,
      terms: terms as Prisma.InputJsonValue,
      clauses: DEFAULT_CLAUSES as unknown as Prisma.InputJsonValue,
      status: AgreementStatus.DRAFT,
    },
  });

  logAudit({
    actorId,
    action: "CREATE",
    targetType: "Agreement",
    targetId: agreement.id,
    details: { proposalId: proposal.id, autoGenerated: true },
  });

  // Notify both parties
  const primaryRepId =
    proposal.cluster.representatives.find((r) => r.isPrimary)?.userId ??
    proposal.cluster.representatives[0]?.userId;

  const recipients = [proposal.investorId, primaryRepId].filter(Boolean) as string[];
  if (recipients.length > 0) {
    await agreementCreatedEvent({
      recipientIds: recipients,
      agreementId: agreement.id,
    });
  }

  realtime.toAgreement(agreement.id, "agreement:created", {
    agreementId: agreement.id,
    proposalId: proposal.id,
    status: agreement.status,
  });

  return agreement;
}

function addMonths(date: Date, months: number): Date {
  const d = new Date(date);
  d.setMonth(d.getMonth() + months);
  return d;
}

function buildAgreementTerms(
  proposal: Proposal & {
    cluster: {
      id: string;
      name: string;
      location: string;
      region: string;
      totalArea: Prisma.Decimal | null;
      cropTypes: string[];
      coordinates: unknown;
    };
    investor: { id: string; name: string; email: string };
  },
  dates: { startDate: Date; endDate: Date }
) {
  return {
    parties: {
      investor: {
        id: proposal.investor.id,
        name: proposal.investor.name,
        email: proposal.investor.email,
      },
      cluster: {
        id: proposal.cluster.id,
        name: proposal.cluster.name,
        location: proposal.cluster.location,
        region: proposal.cluster.region,
        totalArea: proposal.cluster.totalArea?.toString() ?? null,
        coordinates: proposal.cluster.coordinates,
      },
    },
    lease: {
      startDate: dates.startDate.toISOString(),
      endDate: dates.endDate.toISOString(),
      durationMonths: proposal.durationMonths,
      cropIntended: proposal.cropIntended,
    },
    financial: {
      budget: proposal.budget.toString(),
      currency: "ETB",
    },
    negotiatedTerms: proposal.terms,
    supportingDocuments: proposal.documents,
  };
}
